name: Docker build & push

on:
  workflow_dispatch:
    inputs:
      language:
        type: choice
        description: Name of the programming language
        options:
          - golang
      application:
        type: choice
        description: Name of the application
        options:
          - httpserver

jobs:
  docker_build:
    name: "Build Docker image"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout_repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: setup_docker_buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github container registry
        id: login_to_ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          context: "./apps/${{ inputs.language }}/."
          push: true
          tags: ghcr.io/${{ github.actor }}/${{ secrets.PROJECT }}-${{ inputs.application }}-${{ inputs.language }}:${{ github.sha }}
          build-args: "APP_NAME=${{ inputs.application }}"
